apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel-ssh
  # namespace: cloudflare-tunnel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared-tunnel-ssh
  template:
    metadata:
      labels:
        app: cloudflared-tunnel-ssh
    spec:
      hostNetwork: true
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        command: ["cloudflared", "tunnel", "--no-autoupdate", "run"]
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-secret
              key: token-ssh
      restartPolicy: Always
      terminationGracePeriodSeconds: 60